name: Publish to WinGet
on:
  push:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: taers232c.GAMADV-XTD3
          max-versions-to-keep: 5 # keep only latest 5 versions
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}