name: Publish to WinGet
on:
  workflow_dispatch:
env:
  GDN_SUPPRESS_FORKED_BUILD_WARNING: true
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: taers232c.GAMADV-XTD3
          release-tag: v7.05.06
          max-versions-to-keep: 1 # keep only latest versions
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}