name: Publish to WinGet
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: taers232c.GAMADV-XTD3
          release-tag: v6.76.15
          max-versions-to-keep: 5 # keep only latest 5 versions
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}